#pragma once

#define FASTSIMD_FALLBACK_SIMD_LEVEL Level_Scalar

#define FASTSIMD_COMPILE_SCALAR      1
#define FASTSIMD_COMPILE_SSE        000 // Not supported
#define FASTSIMD_COMPILE_SSE2        1
#define FASTSIMD_COMPILE_SSE3        1
#define FASTSIMD_COMPILE_SSSE3       1
#define FASTSIMD_COMPILE_SSE41       1
#define FASTSIMD_COMPILE_SSE42      000
#define FASTSIMD_COMPILE_AVX        000 // Not supported
#define FASTSIMD_COMPILE_AVX2        1
#define FASTSIMD_COMPILE_AVX512F    000
#define FASTSIMD_COMPILE_AVX512VL   000
#define FASTSIMD_COMPILE_AVX512BWQD 000


#define FASTSIMD_CONFIG_GENERATE_CONSTANTS

